# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-31 17:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_itemmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemManager',
        ),
    ]
